spring:

    application:
        name: backend

    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/jnep?serverTimezone=Asia/Seoul
        username: jnepuser
        password: qwe123

    thymeleaf:
        prefix: classpath:/templates/
        suffix: .html

    jpa:
        #database-platform: org.hibernate.dialect.MySQL8Dialect
        #database-platform: org.hibernate.dialect.MySQLDialect
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
                #"[]" 로 감싸지 않으면 특수문자 때문에 에러 발생
                "[format_sql]": true
                
                #logging 에서 로그 출력하므로 주석처리
                #콘솔로 출력
                #show-sql: true
        open-in-view: false

#로그로 출력
logging:
    level:
        "[org.hibernate.SQL]": debug
        #"[org.hibernate.type]": trace
        org:
            hibernate:
                type:
                    descriptor:
                        sql: trace

server:
    port: 8000